name: Checks

on:
    - pull_request

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Cache
              uses: actions/cache@v2
              id: cache
              with:
                  path: '**/node_modules'
                  key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
            - name: Install
              run: yarn --immutable
              if: steps.cache.outputs.cache-hit != 'true'
            - name: Lint
              run: yarn lint

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Cache
              uses: actions/cache@v2
              id: cache
              with:
                  path: '**/node_modules'
                  key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
            - name: Install
              run: yarn --immutable
              if: steps.cache.outputs.cache-hit != 'true'
            - name: Build
              run: yarn build

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Cache
              uses: actions/cache@v2
              id: cache
              with:
                  path: '**/node_modules'
                  key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
            - name: Install
              run: yarn --immutable
              if: steps.cache.outputs.cache-hit != 'true'
            - name: Compile
              run: yarn build
            - name: Run mainnet node in background for integration tests
              run: npx hardhat --tsconfig tsconfig.testing.json node --hostname 127.0.0.1 --fork ${{ secrets.RPC_URL_MAINNET }} &
            - name: Run Polygon node in background for integration tests
              run: npx hardhat --tsconfig tsconfig.testing.json --config hardhat.config.polygon.ts node --hostname 127.0.0.1 --fork ${{ secrets.RPC_URL_POLYGON }} --port 8137 &
            - name: Test
              run: yarn test
env:
    CI: true
    RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
    RPC_URL_POLYGON: ${{ secrets.RPC_URL_POLYGON }}
